-- MySQL Script generated by MySQL Workbench
    -- Mon Nov 23 13:36:05 2020
    -- Model: New Model    Version: 1.0
    -- MySQL Workbench Forward Engineering
SET
    @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
    UNIQUE_CHECKS = 0;
SET
    @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;
SET
    @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    -- -----------------------------------------------------
    -- Schema mydb
    -- -----------------------------------------------------
    -- -----------------------------------------------------
    -- Schema airbabouche
    -- -----------------------------------------------------
DROP
    SCHEMA IF EXISTS `airbabouche`;
    -- -----------------------------------------------------
    -- Schema airbabouche
    -- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbabouche` DEFAULT CHARACTER SET utf8mb4; USE
    `airbabouche`;
    -- -----------------------------------------------------
    -- Table `airbabouche`.`pays`
    -- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`pays`(
    `idPays` INT NOT NULL AUTO_INCREMENT,
    `nom` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`idPays`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;
-- -----------------------------------------------------
-- Table `airbabouche`.`aeroport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`aeroport`(
    `idaeroport` VARCHAR(5) NOT NULL,
    `nom` VARCHAR(50) NOT NULL,
    `ville` VARCHAR(70) NOT NULL,
    `pays` INT NOT NULL,
    PRIMARY KEY(`idaeroport`),
    INDEX `FK_aeroport_pays`(`pays` ASC),
    CONSTRAINT `FK_aeroport_pays` FOREIGN KEY(`pays`) REFERENCES `airbabouche`.`pays`(`idPays`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;
-- -----------------------------------------------------
-- Table `airbabouche`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`personne`(
    `idpersonne` INT NOT NULL AUTO_INCREMENT,
    `nom` VARCHAR(70) NOT NULL,
    `prenom` VARCHAR(70) NOT NULL,
    `dateNaiss` DATE NOT NULL,
    `adresse` VARCHAR(50) NULL DEFAULT NULL,
    `ville` VARCHAR(50) NULL DEFAULT NULL,
    `zipcode` VARCHAR(20) NULL DEFAULT NULL,
    `pays_idPays` INT NOT NULL,
    PRIMARY KEY(`idpersonne`),
    INDEX `fk_personne_pays1_idx`(`pays_idPays` ASC),
    CONSTRAINT `fk_personne_pays1` FOREIGN KEY(`pays_idPays`) REFERENCES `airbabouche`.`pays`(`idPays`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;
-- -----------------------------------------------------
-- Table `airbabouche`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`client`(
    `email` VARCHAR(200) NOT NULL,
    `password` VARCHAR(80) NOT NULL,
    `personne_idpersonne` INT NOT NULL,
    PRIMARY KEY(`personne_idpersonne`),
    UNIQUE INDEX `email_UNIQUE`(`email` ASC),
    CONSTRAINT `fk_client_personne1` FOREIGN KEY(`personne_idpersonne`) REFERENCES `airbabouche`.`personne`(`idpersonne`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;
-- -----------------------------------------------------
-- Table `airbabouche`.`compagnie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`compagnie`(
    `idcompagnie` INT NOT NULL,
    `nom` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`idcompagnie`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;
-- -----------------------------------------------------
-- Table `airbabouche`.`vol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`vol`(
    `idvol` INT NOT NULL AUTO_INCREMENT,
    `place` SMALLINT NOT NULL DEFAULT 300,
    `intitule` VARCHAR(50) NULL,
    `aeroport_depart` VARCHAR(5) NOT NULL,
    `aeroport_arrive` VARCHAR(5) NOT NULL,
    `date_depart` DATETIME NOT NULL,
    `date_arrive` DATETIME NOT NULL,
    `idcompagnie` INT NOT NULL,
    PRIMARY KEY(`idvol`),
    INDEX `FK_vol_aeroport`(`aeroport_depart` ASC),
    INDEX `FK_vol_aeroport_2`(`aeroport_arrive` ASC),
    INDEX `FK_vol_compagnie`(`idcompagnie` ASC),
    CONSTRAINT `FK_vol_aeroport` FOREIGN KEY(`aeroport_depart`) REFERENCES `airbabouche`.`aeroport`(`idaeroport`),
    CONSTRAINT `FK_vol_aeroport_2` FOREIGN KEY(`aeroport_arrive`) REFERENCES `airbabouche`.`aeroport`(`idaeroport`),
    CONSTRAINT `FK_vol_compagnie` FOREIGN KEY(`idcompagnie`) REFERENCES `airbabouche`.`compagnie`(`idcompagnie`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;
-- -----------------------------------------------------
-- Table `airbabouche`.`escale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`escale`(
    `vol_idvol` INT NOT NULL,
    `aeroport_idaeroport` VARCHAR(5) NOT NULL,
    `date_depart` DATETIME NOT NULL,
    `date_arrive` DATETIME NOT NULL,
    PRIMARY KEY(`vol_idvol`, `aeroport_idaeroport`),
    INDEX `fk_escale_aeroport1_idx`(`aeroport_idaeroport` ASC),
    CONSTRAINT `fk_escale_vol1` FOREIGN KEY(`vol_idvol`) REFERENCES `airbabouche`.`vol`(`idvol`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_escale_aeroport1` FOREIGN KEY(`aeroport_idaeroport`) REFERENCES `airbabouche`.`aeroport`(`idaeroport`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;
-- -----------------------------------------------------
-- Table `airbabouche`.`passager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`passager`(
    `idpassager` INT NOT NULL AUTO_INCREMENT,
    `idpersonne` INT NULL DEFAULT NULL,
    PRIMARY KEY(`idpassager`),
    INDEX `FK_passager_personne`(`idpersonne` ASC),
    CONSTRAINT `FK_passager_personne` FOREIGN KEY(`idpersonne`) REFERENCES `airbabouche`.`personne`(`idpersonne`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;
-- -----------------------------------------------------
-- Table `airbabouche`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbabouche`.`reservation`(
    `idvol` INT NOT NULL,
    `client_idpersonne` INT NOT NULL,
    `confirmation` ENUM(
        'Confirm',
        'Pending',
        'Cancel',
        'Refuse'
    ) NOT NULL,
    `personne_idpersonne` INT NOT NULL,
    PRIMARY KEY(`idvol`, `client_idpersonne`),
    INDEX `FK_reservation_vol`(`idvol` ASC),
    INDEX `fk_reservation_client1_idx`(`client_idpersonne` ASC),
    INDEX `fk_reservation_personne1_idx`(`personne_idpersonne` ASC),
    CONSTRAINT `FK_reservation_vol` FOREIGN KEY(`idvol`) REFERENCES `airbabouche`.`vol`(`idvol`),
    CONSTRAINT `fk_reservation_client1` FOREIGN KEY(`client_idpersonne`) REFERENCES `airbabouche`.`client`(`personne_idpersonne`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_reservation_personne1` FOREIGN KEY(`personne_idpersonne`) REFERENCES `airbabouche`.`personne`(`idpersonne`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4; SET
    SQL_MODE = @OLD_SQL_MODE;
SET
    FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET
    UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;